#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# redirect stderr to stdout so it's picked up in the docker logs
exec 2>&1
# all errors will show a line number and the command used to produce the error
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
trap 'echo -e "[ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND"' ERR

APPNAME="$(hostname)/planelog"
APPPATH="/usr/share/planelog/PlaneLog.py"

# -----------------------------------------------------------------------------------
# Now run ligghttpd for real
#
[[ "$LOGLEVEL" != "ERROR" ]] && echo "[$APPNAME][$(date)] Bringing Planelog Up" || true
python3 $APPPATH